@extends('layouts.dashboard')

@section('content')
<div class="content">
    <div class="container-xl">
        <div class="row row-cards">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Dashboard Home</h3>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-success">
                            Hi there! Thank you for using the <code><a href="https://github.com/Proxeuse/fortify-tabler">Proxeuse/fortify-tabler</a></code> FortifyUI preset.
                            We've automatically installed the authentication pages (login, registration, etc.) and the
                            profile edit page. You're now able to edit anything of your likings.
                            This version of Proxeuse/fortify-tabler also features automatic avatars and manual avatar
                            uploads. The default avatar image is generated by the <a href="https://api.proxeuse.com/avatars/" target="_blank">Proxeuse Avatar API</a>,
                            you are free to change this to any other generator.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
